### ISSUE TITLE
Display who reacted with which Reactions

### ISSUE THREAD

**Issue by Milton1688** [Tyrrrz/DiscordChatExporter#392] opened 2020-10-04 02:12 UTC
In the Discord desktop app, when people react to a post, doing a mouseover the reaction will show which people posted that reaction. If more than three people used the same reaction to a post, you must click on the Reactions tab of that post to see them all. Is it possible or practical, to include that information along with everything else that is being exported?

**Comment by Tyrrrz** [comment] 2020-10-05 00:57
Duplicate of #133
The explanation of why it cannot be implemented is in the thread

**Closed by Tyrrrz** 2020-10-05 00:57 UTC
Labels: duplicate
