### ISSUE TITLE
a filter feature

### ISSUE THREAD

**Issue by manwhy** [Tyrrrz/DiscordChatExporter#603] opened 2021-06-06 23:22 UTC
### Flavor

GUI (Graphical User Interface)

### Details

make it so that it only downloads certain messages, maybe messages without the author being a bot, maybe messages being a bot command, maybe messages without certain keywords

**Comment by Tyrrrz** [comment] 2021-06-07 18:00
Duplicate of #160

**Closed by Tyrrrz** 2021-06-07 18:00 UTC
Labels: duplicate
