### ISSUE TITLE
Save and Export Images for Offline Viewing

### ISSUE THREAD

**Issue by TheRenegadist** [Tyrrrz/DiscordChatExporter#161] opened 2019-04-02 09:45 UTC
Would be nice if this also downloaded all images in the channel including avatars and embedded them into the HTML because right now you can save the chat and any images that are backed up externally but everything else doesn't show.

I'm going to be deleting a bunch of channels on April 20, it would be amazing to have this implemented so I can fully back them up without losing anything.

**Comment by Tyrrrz** [comment] 2019-04-03 13:27
Hey there.
This is a duplicate of #21.
You can also work around it by saving the export again in e.g. Chrome, this will download all assets.

**Closed** 2019-04-06 20:20 UTC
Labels: duplicate
