### ISSUE TITLE
OutOfMemoryException (Yes, I know you can use dates)

### ISSUE THREAD

**Issue by TheRenegadist** [Tyrrrz/DiscordChatExporter#228] opened 2019-11-07 02:25 UTC
Trying to pull a chat channel that has been up for years and even though the progress bar finishes when it's outputting the file before finishing it gets an "Out of Memory" error causing the HTML to corrupt.

I realize I can use dates to cut how much it renders but I don't want multiple HTML's for one channel, it should be fixed so it CAN render large/old channels without crashing at the very end. Image below of the error:

![Desktop 11-6-2019 6-24-47 PM-428](https://user-images.githubusercontent.com/31916442/68354996-c52df400-00c2-11ea-8e56-07248b4c63b3.png)

**Comment by Tyrrrz** [comment] 2019-11-07 08:41
Duplicate of #125

**Closed by Tyrrrz** 2019-11-07 08:41 UTC
Labels: duplicate
