### ISSUE TITLE
Option to export messages sent by a specific user only

### ISSUE THREAD

**Issue by UncleBen69** [Tyrrrz/DiscordChatExporter#343] opened 2020-07-27 00:15 UTC
I'm currently trying to export all messages sent from a user in a specific Discord Server.
An filter option to only include users with a certain id would be pretty useful.

Thanks

**Comment by Tyrrrz** [comment] 2020-07-27 10:28
Duplicate of #28

**Closed by Tyrrrz** 2020-07-27 10:28 UTC
Labels: duplicate
