### ISSUE TITLE
Continuous exporting of a channel

### ISSUE THREAD

**Issue by BuyMyMojo** [Tyrrrz/DiscordChatExporter#773] opened 2022-01-13 09:48 UTC
### Details

The ability to keep the exporter monitoring chats for new messages in channels so we can log channels with channel history disabled?

Stay connected to a specific channel and only stop logging when you press a stop button in the GUI or Ctl+C in the CLI?

**Comment by Tyrrrz** [comment] 2022-01-13 22:54
Duplicate of #27 #32 #444 #485 #482 #564 #688 #769

**Closed by Tyrrrz** 2022-01-13 22:54 UTC
Labels: duplicate

**Comment by BuyMyMojo** [comment] 2022-01-14 02:22
Incremental backups and updating past CSVs doesn't allow exporting of channels with message history disabled

**Comment by 96-LB** [comment] 2022-01-14 02:31
It also doesn't allow you to export channels with "read message" permissions disabled. If the server moderators haven't given you the permission to see message history, then you're not supposed to be able to see message history, and this tool doesn't let you bypass that.
