### ISSUE TITLE
Export someone's messages from a server

### ISSUE THREAD

**Issue by pencilbook** [Tyrrrz/DiscordChatExporter#219] opened 2019-10-19 04:51 UTC
I would like to export all of the messages from a certain user from the entire server. This is currently not possible. Let me know if you like the idea.

**Comment by Tyrrrz** [comment] 2019-10-19 09:46
Duplicates of #28

**Comment by Tyrrrz** [comment] 2019-10-19 09:46
Duplicate of #28

**Closed by Tyrrrz** 2019-10-19 09:46 UTC
Labels: duplicate
