### ISSUE TITLE
Error pulling guilds and channels

### ISSUE THREAD

**Issue by GingerDesigne** [Tyrrrz/DiscordChatExporter#833] opened 2022-04-16 06:09 UTC
### Version

v.2.34.0

### Flavor

GUI (Graphical User Interface)

### Details

Hello,

Every time I paste my token into the GUI and click on the arrow I get the same error.
Could you please help? 

### Steps to reproduce

Paste the token
Click on the arrow

**Comment by Tyrrrz** [comment] 2022-04-16 12:56
What is the error?

**Comment by GingerDesigne** [comment] 2022-04-16 14:00
> What is the error?

Greetings Tyrrrz,

I get this error when I paste my token and click on the arrow.
![Error pulling](https://user-images.githubusercontent.com/94997323/163677761-122121c2-baac-43d2-a320-f1c8a4944b76.png)

**Comment by Tyrrrz** [comment] 2022-04-16 14:21
Please try the latest CI build

**Comment by Tyrrrz** [comment] 2022-04-16 14:22
Duplicate of #828

**Closed by Tyrrrz** 2022-04-16 14:21 UTC
Labels: invalid

**Comment by GingerDesigne** [comment] 2022-04-16 14:50
> Please try the latest CI build

Apologies Tyrrrz, but I do not even know how to download CI. When I click on that it takes me to this page:
![image_2022-04-16_175030498](https://user-images.githubusercontent.com/94997323/163679567-5b0ae334-3fa8-445b-9fdd-f6d61610defd.png)

**Comment by Tyrrrz** [comment] 2022-04-16 16:53
@GingerDesigne download the corresponding file from the "artifacts" section below:

https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/2177232347
