### ISSUE TITLE
Capture deleted messages

### ISSUE THREAD

**Issue by PMMEnergy** [Tyrrrz/DiscordChatExporter#476] opened 2021-01-12 22:35 UTC
I use this for looking at server statistics, but when messages are purged/deleted, it messes up the count. Would it be possible to integrate this with discord (similar to the BetterDiscord Message Logger) in a way that captures those messages and stores the data before they are deleted/purged? Or maybe If you could combine new logs with older logs to capture a more complete version, possibly adding an automating feature to the GUI that allows for automatic updates to certain channels' logs at whatever intervals of time you might choose? That would be really awesome, thank you!

**Comment by Tyrrrz** [comment] 2021-01-13 17:36
No, this is out of scope. Likely duplicate of #444

**Closed by Tyrrrz** 2021-01-13 17:36 UTC
Labels: duplicate

**Comment by PMMEnergy** [comment] 2021-01-13 17:51
Ok. Thanks for the reply!
