### ISSUE TITLE
freezes in new versions

### ISSUE THREAD

**Issue by EstoniaEsti** [Tyrrrz/DiscordChatExporter#1126] opened 2023-09-03 06:26 UTC
### Version

2.38-2.40.4

### Flavor

GUI (Graphical User Interface)

### Platform

Windows 10

### Export format

HTML

### Steps to reproduce

Server invite: 
https://discord.gg/p8a3h79T
Channel or message link: https://discordapp.com/channels/678936664021794817/679228462413643795
Export settings: HTML

Steps:
Step 1 - go to the server
Step 2 - export channel in >2.37.2 version
Step 3 - export channel in ≤2.37.2 version

### Details

A lot of people complain that the application freezes and does not work normally - someone assumes that it is because of invites, someone that because of something else. I also ran into this problem and found out that the latest version of the application in which there were no problems is 2.37.2 and there has been no bugfix for many months. When trying to save a channel in html, the application freezes in many cases. I hope the developer will solve this problem, until then I will continue to use 2.37.2.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment] 2023-09-03 09:46
Duplicate of #1103, judging by the context

**Closed by Tyrrrz** 2023-09-03 09:46 UTC
Labels: duplicate
