### ISSUE TITLE
Error Exporting Channel (System.IndexOutOfRangeException)

### ISSUE THREAD

**Issue by Ferretsroq** [Tyrrrz/DiscordChatExporter#938] opened 2022-09-21 19:54 UTC
### Version

v2.36.0

### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

I attempted to export a channel, and was met with the exception shown below:
![IndexOutOfRangeException](https://user-images.githubusercontent.com/9344492/191597498-03ac55af-1934-4d72-b0b0-cc847ce9a006.PNG)

The output file looks like this:
![DCE_output](https://user-images.githubusercontent.com/9344492/191597852-68e6ce8b-e090-42ab-9ce5-1248762fc36c.PNG)

The actual channel continues for 380 messages:
![DCE_channel](https://user-images.githubusercontent.com/9344492/191597901-cd0856a5-9948-456f-b090-96aba416b6a0.PNG)

I can export as .txt just fine. I am using the bot's token with message intents enabled if that matters.

### Steps to reproduce

Run DiscordChatExporter.exe

Select channel to export

Select HTML (light or dark both produce the error)

Export

**Comment by Ferretsroq** [comment] 2022-09-21 20:45
For easier copy/pasting, here is the error from the CLI. It looks mostly the same, but there are a couple differences. Not sure how relevant they are.

```Exporting 1 channel(s)...

Text Channels / game-thread ----------------------------------------   0%

ERROR
System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at DiscordChatExporter.Core.Exporting.Writers.Html.MessageGroupTemplate.ExecuteAsync() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\MiniRazor.CodeGen\MiniRazor.CodeGen.TemplateClassGenerator\MiniRazor_GeneratedTemplate_b3921b55-dbd9-4b4e-949d-2eb968473647.cs:0
  at DiscordChatExporter.Core.Exporting.Writers.Html.MessageGroupTemplate.RenderAsync(TextWriter output, MessageGroupTemplateContext model, CancellationToken cancellationToken)
  at DiscordChatExporter.Core.Exporting.Writers.Html.MessageGroupTemplate.RenderAsync(MessageGroupTemplateContext model, CancellationToken cancellationToken)
  at DiscordChatExporter.Core.Exporting.Writers.HtmlMessageWriter.WriteMessageGroupAsync(IReadOnlyList`1 messages, CancellationToken cancellationToken) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\Writers\HtmlMessageWriter.cs:95
  at DiscordChatExporter.Core.Exporting.Writers.HtmlMessageWriter.WritePostambleAsync(CancellationToken cancellationToken) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\Writers\HtmlMessageWriter.cs:127
  at DiscordChatExporter.Core.Exporting.MessageExporter.ResetWriterAsync(CancellationToken cancellationToken) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\MessageExporter.cs:26
  at DiscordChatExporter.Core.Exporting.MessageExporter.DisposeAsync() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\MessageExporter.cs:64
  at DiscordChatExporter.Core.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\ChannelExporter.cs:79
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.<>c__DisplayClass43_2.<<ExecuteAsync>b__2>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:166
  at DiscordChatExporter.Cli.Utils.Extensions.ConsoleExtensions.StartTaskAsync(ProgressContext progressContext, String description, Func`2 performOperationAsync) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Utils\Extensions\ConsoleExtensions.cs:43
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.<>c__DisplayClass43_1.<<ExecuteAsync>b__1>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:147
  at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.<>c__DisplayClass43_0.<<ExecuteAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:136
  at Spectre.Console.Progress.<>c__DisplayClass27_0.<<StartAsync>b__0>d.MoveNext() in \_\src\Spectre.Console\Live\Progress\Progress.cs:98
  at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in \_\src\Spectre.Console\Live\Progress\Progress.cs:133
  at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in \_\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:40
  at Spectre.Console.Progress.StartAsync[T](Func`2 action) in \_\src\Spectre.Console\Live\Progress\Progress.cs:116
  at Spectre.Console.Progress.StartAsync(Func`2 action) in \_\src\Spectre.Console\Live\Progress\Progress.cs:96
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExecuteAsync(IConsole console, IReadOnlyList`1 channels) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:134
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExecuteAsync(IConsole console, IReadOnlyList`1 channelIds) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:232
  at DiscordChatExporter.Cli.Commands.ExportChannelsCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportChannelsCommand.cs:26
  at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in D:\a\CliFx\CliFx\CliFx\CliApplication.cs:147
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in D:\a\CliFx\CliFx\CliFx\CliApplication.cs:191```

**Comment by Tyrrrz** [comment] 2022-09-21 21:05
Please use the CI build for now. Duplicate of #935. A stable release will be available on Friday.

**Closed by Tyrrrz** 2022-09-21 21:05 UTC
Labels: duplicate

**Comment by Ferretsroq** [comment] 2022-09-21 21:27
Just confirming that using the CI build does complete with no errors. Is it known that embeds with no text content won't render in the html output? 

![noembedoutput](https://user-images.githubusercontent.com/9344492/191613348-174cbffc-8c98-4f64-8216-0bbbe6f40664.PNG)

vs how it looks in discord:

![indiscord](https://user-images.githubusercontent.com/9344492/191613478-1924fc4f-4eb1-4f18-a096-c434072822da.PNG)

**Comment by Tyrrrz** [comment] 2022-09-22 10:32
No it's not @Ferretsroq. Can you check if the embed issue is reproducible with older versions of DCE?

**Comment by Ferretsroq** [comment] 2022-09-22 14:25
The embed works in 2.35.2, 2.33.0, and 2.32.0

**Comment by Tyrrrz** [comment] 2022-09-22 14:38
@Ferretsroq but not 2.36?

**Comment by Ferretsroq** [comment] 2022-09-22 14:38
2.36 experiences the IndexOutOfRange exception so it doesn't render that message at all, and the CI build is shown above where the message appears blank.

**Comment by Tyrrrz** [comment] 2022-09-24 16:55
@Ferretsroq can you please try the latest-most CI build? If that doesn't help, can you get on our Discord server and send me an invite to the server where you're experiencing this problem?

DCE discord: https://discord.gg/2SUWKFnHSm

**Comment by Ferretsroq** [comment] 2022-09-24 17:14
The latest CI build works. Thanks!
