### ISSUE TITLE
Ability to export threads in channels please.

### ISSUE THREAD

**Issue by AntDX316** [Tyrrrz/DiscordChatExporter#888] opened 2022-07-22 11:17 UTC
### Details

Ability to export threads in channels please. I've limited to 500 max channels so I've had to combine around 12 into 1 channel but now I can't export threads. within the channel : (

**Comment by Tyrrrz** [comment] 2022-07-22 11:23
Duplicate of #663

**Closed by Tyrrrz** 2022-07-22 11:23 UTC
Labels: duplicate
