### ISSUE TITLE
Automatic export update

### ISSUE THREAD

**Issue by diyarit** [Tyrrrz/DiscordChatExporter#883] opened 2022-07-09 08:31 UTC
### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

Hi there,

I was wondering if there's a feature or a way to export / save the media / logs automatically by leaving the app running in the background "real time"?

thanks

**Comment by Tyrrrz** [comment] 2022-07-09 10:20
No, there is not.
Duplicate of https://github.com/Tyrrrz/DiscordChatExporter/issues/27 https://github.com/Tyrrrz/DiscordChatExporter/issues/32 https://github.com/Tyrrrz/DiscordChatExporter/issues/444 https://github.com/Tyrrrz/DiscordChatExporter/issues/485 https://github.com/Tyrrrz/DiscordChatExporter/issues/482 https://github.com/Tyrrrz/DiscordChatExporter/issues/564 https://github.com/Tyrrrz/DiscordChatExporter/issues/688 https://github.com/Tyrrrz/DiscordChatExporter/issues/769 #773

**Closed by Tyrrrz** 2022-07-09 10:20 UTC
Labels: duplicate
