### ISSUE TITLE
How can I find my token key?

### ISSUE THREAD

**Issue by m1m2m3mr** [Tyrrrz/DiscordChatExporter#89] opened 2018-08-26 11:07 UTC
I followed the instruction to find my token but i can't find it in Local Storage > discord.com. I swear it was there before. I'm missing something?

![image](https://user-images.githubusercontent.com/20967118/44627599-ef1d4f80-a930-11e8-9ec1-c37f64783fd2.png)

**Comment by DrakeTDL** [comment] 2018-08-26 11:41
Duplicate of #76

**Closed** 2018-08-26 19:32 UTC
Labels: duplicate
