### ISSUE TITLE
Export user list

### ISSUE THREAD

**Issue by teisseire117** [Tyrrrz/DiscordChatExporter#317] opened 2020-06-30 06:42 UTC
Hi,
I wanted to know if you could make possible to export the user list of a server(username and their IDs) ? I think it would be a very nice addition and something in the theme of what your bot is about.
Thank you

**Comment by Tyrrrz** [comment] 2020-06-30 11:24
Hi.
This application is about exporting messages, everything else is out of scope.
Duplicate of #104

**Closed by Tyrrrz** 2020-06-30 11:24 UTC
Labels: duplicate
