### ISSUE TITLE
Few requests

### ISSUE THREAD

**Issue by Ruok2bu** [Tyrrrz/DiscordChatExporter#381] opened 2020-09-22 22:00 UTC
This application is awesome, but i was hoping you would add these features:

- Option to remove Preamble and postamble code from page.
- Limit display of messages to x last messages. So for example if a channel has 100 messages, i can choose to display only the 10 latest ones.

**Comment by Tyrrrz** [comment] 2020-09-27 22:33
> Option to remove Preamble and postamble code from page.

In which format?

> Limit display of messages to x last messages. So for example if a channel has 100 messages, i can choose to display only the 10 latest ones.

Duplicate of #316

**Comment by Ruok2bu** [comment] 2020-09-27 23:58
> > Option to remove Preamble and postamble code from page.
> 
> In which format?
> 
Htmldark but ideally the other themes too so others can use that too.

**Comment by Tyrrrz** [comment] 2020-09-28 19:14
Why do you want it removed?

**Comment by Ruok2bu** [comment] 2020-09-28 20:53
I'm using your application to save news from a specific channel and display it on a website. But having the preamble and postamble visible is adding unneeded information to the page.

**Comment by Tyrrrz** [comment] 2020-09-29 10:18
Well the application is aimed more towards personal use. If you host it on a website, you might do well with a script that uses regex to scrape the preamble/postamble out of the body.

**Closed** 2020-10-02 12:07 UTC
Labels: invalid
