### ISSUE TITLE
Exporting a guild does not export threads

### ISSUE THREAD

**Issue by MycroftHolmes1989** [Tyrrrz/DiscordChatExporter#702] opened 2021-09-04 01:45 UTC
### Version

v2.30.1

### Flavor

CLI (Command Line Interface)

### Details

Currently, exporting a guild does not include any threads in any shape or form. Since exporting a guild is used for saving all the available chat in a certain server, not exporting threads does seem like a huge issue.

### Steps to reproduce

-Step 1: Use Docker version of DiscordChatExporter:stable to exportguild.
-Step 2: Look for threads in the export. None exists.

**Comment by Tyrrrz** [comment] 2021-09-04 11:09
Yes, it's not supported currently. Duplicate of #663

**Closed by Tyrrrz** 2021-09-04 11:09 UTC
Labels: duplicate
