### ISSUE TITLE
The latest version doesn't work

### ISSUE THREAD

**Issue by Jokashi** [Tyrrrz/DiscordChatExporter#942] opened 2022-10-02 14:55 UTC
### Version

2.36.1

### Flavor

GUI (Graphical User Interface)

### Details

Since the latest update, I can't run DiscordChatExporter.exe. When I try to launch it nothing happens. I have to remove it and extract an older version to have it work. Then it updates itself automatically when I close it and I have to come back to the older version again.

### Steps to reproduce

- Install the latest version.
- Try to run DiscordChatExporter.exe
- Nothing happens.

**Comment by Tyrrrz** [comment] 2022-10-02 20:51
Can you try the CI build?

**Comment by Tyrrrz** [comment] 2022-10-02 20:51
Duplicate of #941

**Closed** 2022-10-08 12:37 UTC
Labels: duplicate
