### ISSUE TITLE
Convert from JSON format to HTML

### ISSUE THREAD

**Issue by zeutyx** [Tyrrrz/DiscordChatExporter#493] opened 2021-02-03 16:54 UTC
It'd be cool if you can add an option in the CLI to convert chats exported as JSON to HTML formatted chats, this feature would be useful if we have a custom 3rd party tool that can export chats in JSON format, so we would use DiscordChatExporter to convert them into nicely formated HTML chats.

**Comment by Tyrrrz** [comment] 2021-02-08 19:28
Seems like a duplicate of #281

**Closed by Tyrrrz** 2021-02-08 19:28 UTC
Labels: duplicate
