### ISSUE TITLE
Stream export in real-time

### ISSUE THREAD

**Issue by FreeGoldRush** [Tyrrrz/DiscordChatExporter#482] opened 2021-01-20 22:04 UTC
It would be nice to leave the exporter running and have it (efficiently) stream to a logfile in real-time; appending new messages as they come in.  What is the practicality of this?

**Comment by Tyrrrz** [comment] 2021-01-25 20:25
Duplicate of #27 #32 #295 #444 #476 ?

Essentially, the suggested approach to achieve that is to use the CLI and automate it using scripts or a program to do timeboxed exports. Appending messages to an existing export is out of scope and won't be implemented, sorry.

**Comment by FreeGoldRush** [comment] 2021-01-25 21:54
That's what I'm doing now.  The only issue is the frequency of calls to Discord.  I assumed a webhook would be friendlier.  Is running the CLI every 10 or 20 seconds to export the last 10 or 20 seconds of messages reasonable?  What level of activity is likely to irritate someone at Discord and cause an account block?

**Comment by Tyrrrz** [comment] 2021-01-27 16:53
If you start sending too many requests, Discord will return 429 and DCE will wait for the time specified in the headers, so it should be fine. My suggestion is to try and find out ;)

**Comment by Tyrrrz** [comment] 2021-01-27 16:53
Also webhook or not doesn't matter, since you will still need additional requests to get the messages and other things.

**Closed** 2021-02-10 21:36 UTC
Labels: duplicate
