### ISSUE TITLE
This shit could save me if I saved it

### ISSUE THREAD

**Issue by kirkgutierrdd** [Tyrrrz/DiscordChatExporter#303] opened 2020-05-20 23:54 UTC
Anyways can you make the software keep pictures as base64 encode 
so that way the picture wont be hosted on dickord servers?

**Comment by RenanYudi** [comment] 2020-05-20 23:54
[Try this for now](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Storing-HTML-locally)

**Comment by kirkgutierrdd** [comment] 2020-05-20 23:56
> [Try this for now](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Storing-HTML-locally)

Good idea, also would like to see something of saving all of your people hash id's

**Comment by RenanYudi** [comment] 2020-05-20 23:57
> your people hash id's

You mean User IDs?

**Comment by Tyrrrz** [comment] 2020-05-22 20:42
Duplicate of #1 and #21

**Closed by Tyrrrz** 2020-05-22 20:42 UTC
Labels: duplicate
