### ISSUE TITLE
Merge Existing Dumps

### ISSUE THREAD

**Issue by Zopolis4** [Tyrrrz/DiscordChatExporter#769] opened 2022-01-10 08:16 UTC
### Details

Currently, I back up a few servers every two weeks in html format. However, these are large servers, and the dumps quickly grow in size. A feature to merge multiple dumps together, removing messages that were present in both and just adding the new messages onto the edge of the old ones would be greatly appreciated. (for deleted messages, just add a little line at the bottom of the message detailing when it was deleted, and for edited the same as well as showing both the original and edited content.) I have looked into implementing this feature with an external tool, but I found parsing the exported html to be too difficult without knowledge of the original tool.

**Comment by Tyrrrz** [comment] 2022-01-10 13:41
Updating existing exports is out of scope. Additionally, it would be unadvisable anyway since the files would quickly grow too large to open in a browser (hence why partitioning feature was added).

Duplicate of #564 #444 #295 #32

**Closed by Tyrrrz** 2022-01-10 13:41 UTC
Labels: duplicate
