### ISSUE TITLE
Exporter crashes

### ISSUE THREAD

**Issue by Applemiu** [Tyrrrz/DiscordChatExporter#129] opened 2018-12-26 12:52 UTC
The app worked fine yesterday when I downloaded a whole channel. Today I was trying to download only a week's worth of messages:
![2018-12-26 13_47_17-discordchatexporter v2 8 0 0](https://user-images.githubusercontent.com/6752790/50446419-29b1eb80-0915-11e9-959f-e56b05ea5c05.png)

After the app has done exporting, I get the following error message:

![2018-12-26 13_47_47-error occured](https://user-images.githubusercontent.com/6752790/50446447-40f0d900-0915-11e9-9f85-992b52dee2f1.png)

**Comment by RenanYudi** [comment] 2018-12-26 20:46
Duplicate of #127

**Closed** 2018-12-30 14:41 UTC
Labels: duplicate
