### ISSUE TITLE
Please may the ability to export to multiple formats at once be added?

### ISSUE THREAD

**Issue by UnpilotedRebuilt1** [Tyrrrz/DiscordChatExporter#370] opened 2020-08-29 12:15 UTC
At the moment if I desired to export to multiple formats I'd have to do it one after the other manually. This can double or even quintuple the time needed to do an export to multiple formats compared to a single format export.

I'm not a developer so I don't really know how this app fetches it information depending on the format you've selected however would it be possible to select multiple export types and only fetch the information from Discord once?

**Comment by Tyrrrz** [comment] 2020-08-29 12:50
Hey, thanks for the suggestion.

This issue is a duplicate of #265.

**Closed by Tyrrrz** 2020-08-29 12:50 UTC
Labels: duplicate
