### ISSUE TITLE
Support for Message Components

### ISSUE THREAD

**Issue by marens101** [Tyrrrz/DiscordChatExporter#814] opened 2022-02-18 09:51 UTC
### Details

Currently, DiscordChatExporter has no support for Message Components, and as such those components simply don't appear in exports. Most notably, this means buttons don't appear, but it also affects other components such as select menus. 

Since Discord is clearly pushing interactions (and therefore components) as seen by their decision to make reading any message a privilaged intent, components (or lack of them) are going to become a lot more noticable in exports. I would suggest adding them in, however this does present another problem:
Buttons will be fine, as they're just another visual element. Select menus though, and the new Modals, would require adding user interaction to the final export to a degree that hasn't been done so far (both require actually interacting with them to actually see all the information). At this point I feel that it would be worth discussing whether maintaining this functionality is actually particurlarly important, or if an alternative way of presenting them should be used instead to display their full content inline with the rest of the transcript.

**Comment by Tyrrrz** [comment] 2022-02-18 13:16
Duplicate of #642

**Closed by Tyrrrz** 2022-02-18 13:16 UTC
Labels: duplicate

**Comment by marens101** [comment] 2022-02-18 21:40
I was thinking it was weird to not see an existing issue for that, must've missed it.
