### ISSUE TITLE
Sort DCE Channels By Date

### ISSUE THREAD

**Issue by Keroror** [Tyrrrz/DiscordChatExporter#526] opened 2021-03-19 04:12 UTC
It would be nice if there was a functionality to sort the channels and dms by last message sent for instance, I think that would come in quite handy for not having to scroll a mile down to find what I need.

**Comment by Tyrrrz** [comment] 2021-03-19 15:01
Duplicate of #271

**Closed by Tyrrrz** 2021-03-19 15:01 UTC
Labels: duplicate
