### ISSUE TITLE
Can't get discord tokens anymore

### ISSUE THREAD

**Issue by ipoopedmypantsuups** [Tyrrrz/DiscordChatExporter#855] opened 2022-05-21 04:57 UTC
### Version

All Known Versions

### Flavor

GUI (Graphical User Interface)

### Details

Discord made a change that renders typical token-retrievable impossible

Is there a fix for this, please?

### Steps to reproduce

- Login to Discord in a web browser
- Open Inspect element
- Try to find "token" under Local Storage
- Fail, because tokens are now encrypted and no longer shown in the local storage db anymore

**Comment by Tyrrrz** [comment] 2022-05-21 10:26
Duplicate of #835?

**Comment by hyzchip** [comment] 2022-05-27 19:03
I have been using the "responsive design mode" in Firefox to get the token.  The token suddenly appears in "local storage" when this mode is enabled, and instantly vanishes once it is disabled again.  I am not sure if this trick works in Chrome or other browsers, though.

**Closed** 2022-05-29 10:01 UTC
Labels: duplicate
