### ISSUE TITLE
Multiple / Mass Export

### ISSUE THREAD

**Issue by jorelking** [Tyrrrz/DiscordChatExporter#105] opened 2018-10-07 14:28 UTC
Is it possible to add a feature to mass export all of your DMs in 1 go instead of clicking multiple times per client? I feel like this would make like so much easier if this is possible. Thanks, love the program!

**Comment by RenanYudi** [comment] 2018-10-07 14:57
Related to [#12](https://github.com/Tyrrrz/DiscordChatExporter/issues/12)

**Comment by Tyrrrz** [comment] 2018-10-07 17:10
Yes, duplicate of #12

**Closed by Tyrrrz** 2018-10-07 17:10 UTC
