### ISSUE TITLE
[ENHANCEMENT] Show the username of people who has reacted to a message

### ISSUE THREAD

**Issue by MycroftHolmes1989** [Tyrrrz/DiscordChatExporter#608] opened 2021-06-16 17:00 UTC
### Export format

HTML

### Details

Currently, in HTML format, it is not possible to check who has reacted to a message. The HTML shows the reaction emojis and the number of reactions, but not the ones who have reacted. It would be helpful if it was possible to include the username of people who have reacted to a particular message.

**Comment by Tyrrrz** [comment] 2021-06-16 20:47
Duplicate of #133

**Closed by Tyrrrz** 2021-06-16 20:47 UTC
Labels: duplicate
