### ISSUE TITLE
export with referrenced media error :<input>(127,101):error: unexpected exception when calling ResolveURL

### ISSUE THREAD

**Issue by jpfl** [Tyrrrz/DiscordChatExporter#341] opened 2020-07-25 19:57 UTC
Hello,
I am using the latest version (it just prompted me today for the update) of the tool running on windows 10pro on two of my discord accounts. and today, for the first time, used the export referrenced media.
in various servers and also private messages the extraction process shows this error during the task: export with referrenced media error :<input>(127,101):error: unexpected exception when calling ResolveURL

then when clicking OK on the dialog  box the discord exporter exits.
when selecting multiple chats or servers this is hard to pinpoint as most have the same minute as last changed file date.
screenshot of the error dialog: https://i.imgur.com/io8GriV.png

the error also happened extraction a single private conversation. though it's a dialog from over a year with many shared images, small files and urls in it. i just wanted to preserve it for the future but cannot continue with the error. let me know if there is something i can do to better debug this. like some hidden log feature or some log file for me to find and provide to you.

**Comment by jpfl** [comment] 2020-07-25 19:59
it would greatly help if the program would just continue with the extraction after clicking the error message away. it would not matter to me if a single channel or message is missing the media.
though if somehow this could be shown in more detail what exactly has caused the error I could download this specific media item manually.

**Comment by Tyrrrz** [comment] 2020-07-25 20:33
Try this build: https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/182487470

**Comment by Tyrrrz** [comment] 2020-07-25 20:33
Duplicate of #332

**Closed by Tyrrrz** 2020-07-25 20:33 UTC
Labels: duplicate

**Comment by jpfl** [comment] 2020-07-25 22:41
> Try this build: https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/182487470

thank you this works without the error.
in order to pinpoint the many exported media files and many are double (like different releases of tools shared on discord) it would help if there could be a feature to have a timestamp added in the beginning of each media file like YYMMDD-HHMM to easily find the part in the message history where this file is linked from.
