### ISSUE TITLE
Export hangs / stops / freezes at some point during export

### ISSUE THREAD

**Issue by Violxnce** [Tyrrrz/DiscordChatExporter#1097] opened 2023-06-23 16:36 UTC
### Version

v2.40.0

### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

When exporting as HTML (dark) the export of: All Direct Messages at once (ctrl + a), a single DM or a Server Channel the export will just stop and not go further. Exporting via TXT works without issues.
Tested exporting to HDD & NVMe SSD

### Steps to reproduce

Step 1. Paste DC Token (personal, not BOT)
Step 2. Select Chat(s) or Channel
Step3. Export as HTML (dark)

**Comment by Tyrrrz** [comment] 2023-08-07 15:27
Seems like a duplicate of #1021 and potentially might be related to #1103

**Closed by Tyrrrz** 2023-08-07 15:27 UTC
Labels: duplicate
