### ISSUE TITLE
Error during export: Cannot read the specified JSON element as a non-empty and non-whitespace string value.

### ISSUE THREAD

**Issue by Feathered-Serpent** [Tyrrrz/DiscordChatExporter#748] opened 2021-12-15 10:44 UTC
### Version

v2.31.0

### Flavor

CLI (Command Line Interface)

### Details

I let several exports running over night (over night because I downloaded media as well).

My command line was basically:
DiscordChatExporter.Cli.exe exportall -t "<token here>" -f HtmlLight -o "C:\Discord Exports\%%G\%%T\%%C (%%a).html" --media --dateformat "yyyy-MM-dd HH:mm:ss" --after "2020-01-01 00:00:00.0000" --before "2020-12-31 23:59:59.9999"

This morning I came back to this error message, when I tried to export 2020:
```
ERROR
System.InvalidOperationException: Cannot read the specified JSON element as a non-empty and non-whitespace string value.
  at JsonExtensions.Reading.StringExtensions.GetNonWhiteSpaceString(JsonElement element) in \_\JsonExtensions\Reading\StringExtensions.cs:55
  at DiscordChatExporter.Core.Discord.Data.Emoji.Parse(JsonElement json) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Discord\Data\Emoji.cs:57
  at DiscordChatExporter.Core.Discord.Data.Reaction.Parse(JsonElement json) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Discord\Data\Reaction.cs:14
  at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
  at DiscordChatExporter.Core.Discord.Data.Message.Parse(JsonElement json) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Discord\Data\Message.cs:0
  at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
  at System.Linq.Enumerable.ReverseIterator`1.ToArray()
  at DiscordChatExporter.Core.Discord.DiscordClient.GetMessagesAsync(Snowflake channelId, Nullable`1 after, Nullable`1 before, IProgress`1 progress, CancellationToken cancellationToken)+MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Discord\DiscordClient.cs:0
  at DiscordChatExporter.Core.Discord.DiscordClient.GetMessagesAsync(Snowflake channelId, Nullable`1 after, Nullable`1 before, IProgress`1 progress, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
  at DiscordChatExporter.Core.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\ChannelExporter.cs:45
  at DiscordChatExporter.Core.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\ChannelExporter.cs:45
  at DiscordChatExporter.Core.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\ChannelExporter.cs:80
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.<>c__DisplayClass43_2.<<ExecuteAsync>b__2>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:94
  at DiscordChatExporter.Cli.Utils.Extensions.ConsoleExtensions.StartTaskAsync(ProgressContext progressContext, String description, Func`2 performOperationAsync) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Utils\Extensions\ConsoleExtensions.cs:49
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.<>c__DisplayClass43_1.<<ExecuteAsync>b__1>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:100
  at DiscordChatExporter.Core.Utils.Extensions.AsyncExtensions.<>c__DisplayClass2_0`1.<<ParallelForEachAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Utils\Extensions\AsyncExtensions.cs:49
  at DiscordChatExporter.Core.Utils.Extensions.AsyncExtensions.ParallelForEachAsync[T](IEnumerable`1 source, Func`2 handleAsync, Int32 degreeOfParallelism, CancellationToken cancellationToken) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Utils\Extensions\AsyncExtensions.cs:35
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.<>c__DisplayClass43_0.<<ExecuteAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:71
  at Spectre.Console.Progress.<>c__DisplayClass27_0.<<StartAsync>b__0>d.MoveNext() in \_\src\Spectre.Console\Live\Progress\Progress.cs:103
  at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in \_\src\Spectre.Console\Live\Progress\Progress.cs:138
  at Spectre.Console.Internal.DefaultExclusivityMode.Run[T](Func`1 func) in \_\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:44
  at Spectre.Console.Progress.StartAsync[T](Func`2 action) in \_\src\Spectre.Console\Live\Progress\Progress.cs:121
  at Spectre.Console.Progress.StartAsync(Func`2 action) in \_\src\Spectre.Console\Live\Progress\Progress.cs:101
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExecuteAsync(IConsole console, IReadOnlyList`1 channels) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:69
  at DiscordChatExporter.Cli.Commands.ExportAllCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportAllCommand.cs:38
  at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in \home\runner\work\CliFx\CliFx\CliFx\CliApplication.cs:147
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in \home\runner\work\CliFx\CliFx\CliFx\CliApplication.cs:191
```

In the console window it listed all 213 channels like it did with e.g. 2017, where no error occured. So I can't even tell in which channel it happened, as it also created many output files.

### Steps to reproduce

I don't actually know what to write in there. I can try not to export all but single servers, but would that help if they're private servers?

**Comment by Tyrrrz** [comment] 2021-12-15 13:33
Try the latest CI build

**Comment by Tyrrrz** [comment] 2021-12-15 13:35
Duplicate of #747

**Closed** 2021-12-15 13:35 UTC
Labels: bug
