### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by HiAlexey** [Tyrrrz/DiscordChatExporter#206] opened 2019-09-05 15:52 UTC
A long-time user of this program, love your osu! helper program as well. I have never needed to create a Github account but I wanted to report this issue, it only happens when exporting from one particular person. I am unsure if it's because there is just too much for it to export but unfortunately it fails when it should complete. Here is the error in question if it helps at all. 

![2019-09-05_11-49-15](https://user-images.githubusercontent.com/54950969/64357770-4ab5fa80-cfd3-11e9-9d6e-8fafa83e6d81.png)

**Comment by RenanYudi** [comment] 2019-09-05 16:00
Since DCE caches the content in RAM, large channels can make your computer run out of memory. It’s a [known issue](https://github.com/Tyrrrz/DiscordChatExporter/issues/125#issuecomment-448553586), date ranges or partitioning might help.

**Comment by Tyrrrz** [comment] 2019-09-13 20:13
Hi, this is a known issue and hopefully I will have time to fix it soon.
This is a duplicate of #125

**Closed by Tyrrrz** 2019-09-13 20:13 UTC
Labels: duplicate
