### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by MilkGames** [Tyrrrz/DiscordChatExporter#106] opened 2018-10-13 18:42 UTC
So, think it'll be possible to make a Linux version? I'm not familiar with C#, so I wouldn't know.

**Comment by Tyrrrz** [comment] 2018-10-14 17:49
The CLI is already crossplatform (via mono, will be truly crossplatform soon), but I have no plans to make GUI available for any other platforms.

**Comment by Tyrrrz** [comment] 2018-10-14 17:49
Duplicate of #101

**Closed** 2018-10-14 19:31 UTC
Labels: duplicate
