### ISSUE TITLE
Mentions in chat showing up as "Unknown" in JSON exports

### ISSUE THREAD

**Issue by aws-avocado** [Tyrrrz/DiscordChatExporter#939] opened 2022-09-27 07:32 UTC
### Version

ver 2.36.1

### Flavor

GUI (Graphical User Interface)

### Export format

JSON

### Details

I was exporting one of my channels, but mentioned users are returned as "Unknown" instead of the names in the mention.

The exported JSON looks like this when it comes to the line with their names.

 --- "description": "**User:** @Unknown\n**Amount:** -- Where "Unknown" is supposed to be their name.

Attached screenshot of the what log is supposed to export.
![Screenshot 2022-09-27 at 3 30 32 PM](https://user-images.githubusercontent.com/99958620/192462426-b4d50627-68d1-45c5-8c08-cafb2278d992.png)

### Steps to reproduce

1. Choose channel on Discord.
2. Click on Export icon
3. Choose JSON format.
4. Click on Export.

**Comment by Tyrrrz** [comment] 2022-09-27 12:49
Duplicate of #304

**Closed by Tyrrrz** 2022-09-27 12:49 UTC
Labels: duplicate
