### ISSUE TITLE
Discord Reactions Export Support

### ISSUE THREAD

**Issue by QuantumRange** [Tyrrrz/DiscordChatExporter#856] opened 2022-05-24 08:52 UTC
### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Export format

JSON

### Details

Currently, the program exports only the number of responses, but I would like to see which people have all responded.

**Comment by Tyrrrz** [comment] 2022-05-24 12:09
Duplicate of #133

**Closed by Tyrrrz** 2022-05-24 12:09 UTC
Labels: duplicate
