### ISSUE TITLE
Texts with formatting in a quote badly integrated

### ISSUE THREAD

**Issue by Kwakoxium** [Tyrrrz/DiscordChatExporter#797] opened 2022-01-29 02:13 UTC
### Version

2.32.0

### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

Hi!

I noticed an error regarding the text with formatting in the quotes when exporting to HTML. These are incorrectly placed and end up on the side, away from the unformatted text, which is in the right place.

How it should appear:
![Screenshot 2022-01-29 at 03-01-20 Discord - A New Way to Chat with Friends Communities](https://user-images.githubusercontent.com/87956094/151643161-66ef686c-9380-4073-bb49-bf82113b9e77.png)

How it appears:
![Screenshot 2022-01-29 at 03-01-45 Serveur test - général](https://user-images.githubusercontent.com/87956094/151643180-b13fbfe0-acf6-44cd-a840-bf056288a027.png)

### Steps to reproduce

It's very simple, just write a text, add some formatting to it and turn it into a quote. Once the channel containing the text is converted to HTML, the problem is easily visible. :D

**Comment by Kwakoxium** [comment] 2022-01-29 03:26
Another thing I just noticed is that the problem seems to occur when there are at least three or more lines.

**Comment by Tyrrrz** [comment] 2022-01-30 03:30
Duplicate of #756

**Closed by Tyrrrz** 2022-01-30 03:30 UTC
Labels: duplicate
