### ISSUE TITLE
Show invitation information

### ISSUE THREAD

**Issue by Kwakoxium** [Tyrrrz/DiscordChatExporter#694] opened 2021-08-29 15:34 UTC
### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

I noticed that there was no information under the invitation links, no integration.

I did some testing and this is how it appears in the HTML format:
![Screenshot 2021-08-29 at 14-59-27 Serveur 1 - général](https://user-images.githubusercontent.com/87956094/131256078-0ef975c3-3d90-486f-9f27-48de9cf4ba9e.png)

And here is what should be visible:
![Screenshot 2021-08-29 at 14-59-27 Serveur 1 - général 2](https://user-images.githubusercontent.com/87956094/131256120-41fc53da-340f-4f14-ad71-2e0f9736fe57.png)

**Comment by Tyrrrz** [comment] 2021-08-29 16:06
Duplicate of #649

**Closed by Tyrrrz** 2021-08-29 16:06 UTC
Labels: duplicate
