### ISSUE TITLE
Access Forbidden

### ISSUE THREAD

**Issue by Dominomatic** [Tyrrrz/DiscordChatExporter#520] opened 2021-03-10 11:46 UTC
Hello,

With some exports I get the message “access is forbidden” what can this be?

I use the latest version for windows the GUI version.

Thanks for this great tool.

**Comment by Tyrrrz** [comment] 2021-03-11 19:20
Most likely you don't have permissions to read the channel or the channel's history.
Duplicate of #468 #464

**Closed** 2021-03-11 19:20 UTC
Labels: duplicate
