### ISSUE TITLE
Export Message From Past Time Period And/or Number of Previous Messages

### ISSUE THREAD

**Issue by stanleyshly** [Tyrrrz/DiscordChatExporter#667] opened 2021-07-29 20:22 UTC
### Details

Exporting old/very active channels can take a very very long time, and sometimes, I just want to save the most recent messages, such as message in the past 24 hours, or the most recent conversation I had with someone, such as the previous 500 messages, for example.

What do y'all think of adding a feature to export messages from the previous x time period, or the previous y messages, in order to reduce export times?

**Comment by 96-LB** [comment] 2021-07-29 20:24
Number of messages doesn't yet exist as an option, but you can export date ranges using the options menu on GUI or flags on the CLI. Check out the [wiki](https://github.com/Tyrrrz/DiscordChatExporter/wiki/GUI%2C-CLI-and-Formats-explained) for more information.

**Comment by Tyrrrz** [comment] 2021-07-30 13:27
Duplicate of #316

**Closed by Tyrrrz** 2021-07-30 13:27 UTC
Labels: duplicate
