### ISSUE TITLE
System.InvalidCastException when archiving large channels

### ISSUE THREAD

**Issue by b1k** [Tyrrrz/DiscordChatExporter#180] opened 2019-06-04 18:49 UTC
![DiscordChatExporter_FBlguTPj5r](https://user-images.githubusercontent.com/38332801/58905483-e0da3c00-86d7-11e9-8eb3-dd510610a696.png)

**Comment by Tyrrrz** [comment] 2019-06-04 18:57
Duplicate of #179

**Comment by Tyrrrz** [comment] 2019-06-04 18:58
Please provide some info and the linked issue. If you know how to consistently replicate this, please also share. :)

**Closed by Tyrrrz** 2019-06-04 18:57 UTC
Labels: duplicate

**Comment by b1k** [comment] 2019-06-04 19:21
> Please provide some info in the linked issue. If you know how to consistently replicate this, please also share. :)

To replicate I tried downloading this channel with about 30K messages and every time it reaches halfway this error comes up, so i guess certain messages cause this to happen?
