### ISSUE TITLE
Option to Localy Save Images, Attachements, etc.

### ISSUE THREAD

**Issue by Ryonez** [Tyrrrz/DiscordChatExporter#291] opened 2020-04-15 07:25 UTC
I've noticed that currently only text is saved. Considering that you can share multimedia on Discord, and you can't rely on the links to stay forever, the fact only text is being saved is leaving the backups made by DiscordChatExporter incomplete.

I think it's very important to be able to back up all components of a message so you have them if the original were to disappear.

**Comment by Tyrrrz** [comment] 2020-04-15 07:57
Duplicate of #21

**Closed by Tyrrrz** 2020-04-15 07:57 UTC
Labels: duplicate
