### ISSUE TITLE
Exporting bot messages that contain @user mentions takes way, way too long

### ISSUE THREAD

**Issue by nadir7379** [Tyrrrz/DiscordChatExporter#749] opened 2021-12-15 16:02 UTC
### Version

v.2.31.0

### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Export format

HTML, TXT, JSON, CSV

### Details

One of the chats I am trying to export contains the following info:

![image](https://user-images.githubusercontent.com/1503657/146219289-995dc15f-507d-4e2e-917e-88e3626065e9.png)

This is a bot, InviteManager, which is @mentioning users when they enter the server.
The server has around 300.000 users. The bot sends around 1000-2000 messages every day in that specific chat.

I am trying to export this chat, but it's taking way too long. Comparison:

I tried exporting another chat, which did __not__ contain @mentions . I exported around 400.000 messages in 10-15 minutes.
When trying to export this chat, which is also around 400.000 messages (for the time period that I chose), the bar literally barely moves. 

![image](https://user-images.githubusercontent.com/1503657/146220559-4a39176d-b56a-42bf-a637-3a88139c751c.png)

This ^ is after 4-5 hours of exporting. I think, to let it scrape till the very end, it will take a couple of days (where I need to run the program 24/7).

Is there anything I can do speeden the process? So far, it seems exporting in different filetypes doesn't work (html, txt, etc.).

Love to hear =) 
Nadir

### Steps to reproduce

Step 1: Select channel
Step 2: Edit the settings in DiscordChatExporter, select a certain timeframe
Step 3: Export and wait (taking too long)

**Comment by Tyrrrz** [comment] 2021-12-15 16:19
The issue is caused by this block:

https://github.com/Tyrrrz/DiscordChatExporter/blob/271a478a0e57c9400fe465631247c75f1b44d01e/DiscordChatExporter.Core/Exporting/ChannelExporter.cs#L58-L71

We are doing case-by-case requests to `GetGuildMemberAsync(...)` like that because bot mentions don't embed information about the mentioned user (e.g. their name). I'm not 100% sure if this is still the case, needs checking out.

An alternative would be to get all guild members at once. We can get 1000 members per request, which means we'll need 300 requests for this case. This is obviously better than 300000 requests we're otherwise making now. The problem, however, is that if the exported channel does not have many mentions, then we'd be wasting a lot of requests for no reason.

A yet another, more clever, alternative would be to utilize the [`/guilds/id/members`](https://discord.com/developers/docs/resources/guild#list-guild-members) endpoint with the `after` parameter. We can make a request with `after` set to `mentionedUser.Id - 1` (to ensure the user we're interested in is going to be included) and get that particular member along with 999 others. That would drastically reduce the number of requests we'd need to make without incurring extra overhead. Of course, the downside is that this endpoint requires the `GUILD_MEMBERS` permission, which might not always be available, so we might still need to fall back to getting a single guild member in case of failure.

**Comment by Tyrrrz** [comment] 2021-12-15 16:30
@nadir7379 is the channel you're having issues with public?

**Comment by nadir7379** [comment] 2021-12-15 16:31
> @nadir7379 is the channel you're having issues with public?

@Tyrrrz Hi there, thanks for your reply and potential solutions.

The channel is not public.

**Comment by Tyrrrz** [comment] 2021-12-15 17:26
@nadir7379 try CI build from here as a temporary workaround: https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/1583675518

See if it's any faster

**Comment by nadir7379** [comment] 2021-12-15 20:46
> @nadir7379 try CI build from here as a temporary workaround: https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/1583675518
> 
> See if it's any faster

@Tyrrrz thanks so much for the CI build, that _definitely_ did the job! I scraped those 380.000 messages in about an hour now =) 

Thanks for your work, dedication & fast reply times, it's appreciated a lot.

**Comment by Tyrrrz** [comment] 2021-12-16 14:50
Reopening since the underlying problem isn't fixed, it's just a workaround

**Comment by Tyrrrz** [comment] 2023-02-14 16:33
So, as it turns out, the [List Guild Members](https://discord.com/developers/docs/resources/guild#list-guild-members) endpoint is not accessible by user accounts.

That means we're forced to either make the requests on per-member basis (as we do now), or disable member resolving altogether for mentions. I think both are suboptimal solutions, but given that this issue only really manifests when exporting a channel with a _massive_ amount of user mentions, we can probably classify this as an unsupported edge case.

For that reason, I'm closing this issue as out-of-scope.

**Closed by Tyrrrz** 2023-02-14 16:33 UTC
Labels: bug, help wanted, wontfix
