### ISSUE TITLE
Error pulling guilds and channels

### ISSUE THREAD

**Issue by WolfDorsey** [Tyrrrz/DiscordChatExporter#837] opened 2022-04-24 17:25 UTC
### Version

v2.30.1

### Flavor

GUI (Graphical User Interface)

### Export format

HTML

### Details

I keep getting the _Error pulling guilds and channels_ every time I enter my token, I'm not completely sure what i am doing wrong if i am doing anything wrong?
![Error pulling guilds and channels v2 30 1](https://user-images.githubusercontent.com/104318181/164988509-f4d5d21c-4cf2-42d2-be59-aa840d8ff586.png)

### Steps to reproduce

- Open Discord and copy token
- Past token into DiscordChatExporter
- Removes the speech marks from the token " "
- Press the arrow button and then the error pops up

**Comment by Tyrrrz** [comment] 2022-04-24 17:34
Hey, can you try taking your token and then removing `dQw4w9WgXcQ` in the beginning? See if it works

**Comment by Tyrrrz** [comment] 2022-04-24 17:37
Also duplicate of #835

**Closed** 2022-04-27 10:50 UTC
Labels: duplicate
