### ISSUE TITLE
large error message after downloading

### ISSUE THREAD

**Issue by kelvinwop** [Tyrrrz/DiscordChatExporter#488] opened 2021-01-26 22:02 UTC
![image](https://user-images.githubusercontent.com/30770221/105911425-cad96780-5fef-11eb-80f5-99054ff54e7a.png)

**Comment by kelvinwop** [comment] 2021-01-26 22:50
![image](https://user-images.githubusercontent.com/30770221/105916515-a1700a00-5ff6-11eb-817f-b7c83690f17b.png)

**Comment by Tyrrrz** [comment] 2021-01-27 17:08
Duplicate of #413 and #478 #479.
You can download the latest CI build that fixes the latter.

**Closed by Tyrrrz** 2021-01-27 17:08 UTC
Labels: duplicate
