### ISSUE TITLE
System.OutOfMemoryException when exporting a moderately large channel

### ISSUE THREAD

**Issue by Yumi08** [Tyrrrz/DiscordChatExporter#221] opened 2019-10-23 06:38 UTC
Tried exporting a channel with 1,761,059 messages in it, but got this at about 1/5 of the way
![image](https://user-images.githubusercontent.com/34748443/67364755-2b9d0900-f53e-11e9-8a72-aa284ffffe53.png)

I have 32GB RAM, so I definitely assume it wasn't an issue with that.
I actually had this same issue with the same channel just a few months ago, and was hoping an update would fix it by now.
Also, I was able to export a 302,818 message channel just beforehand, so it's safe to assume the limit is in between that and 1,761,059.

It'd be greatly appreciated if this be fixed, Cause it really gets in the way of what I'm trying to do with the program. Thanks!

Edit: Just read the issue about the memory streaming. Probably would fix this issue. I'll leave it open just in case, but feel free to close it if that is the case.

**Comment by Tyrrrz** [comment] 2019-10-23 08:07
Hi
It's a duplicate of #125

**Closed by Tyrrrz** 2019-10-23 08:07 UTC
Labels: duplicate
