### ISSUE TITLE
Verbose option

### ISSUE THREAD

**Issue by sus-impost0r** [Tyrrrz/DiscordChatExporter#876] opened 2022-06-22 13:09 UTC
### Flavor

CLI (Command Line Interface)

### Details

It would be very nice to have a better understanding of what DCE is doing. A verbose option, perhaps `--verbose` or simply `-v`, or both, would be nice. It would also be cool if one could choose which file descriptor "normal" output and verbose output are written to, if this ever gets added, perhaps as an argument to the verbose option. Unfortunately, I don't have enough knowledge in C# to add this myself.

**Comment by Tyrrrz** [comment] 2022-06-27 15:21
Going to close it as duplicate of that issue

**Closed by Tyrrrz** 2022-06-27 15:21 UTC
Labels: duplicate
