### ISSUE TITLE
CSV doesn't gather embedded content

### ISSUE THREAD

**Issue by Meanski** [Tyrrrz/DiscordChatExporter#527] opened 2021-03-20 22:27 UTC
When using the CSV export, it currently doesn't show anything in the content column if the message is an embed from a bot and/or webhook.

**Comment by Tyrrrz** [comment] 2021-03-21 13:20
Yes, this is intentional.
Duplicate of #431 #225 #237.

**Closed by Tyrrrz** 2021-03-21 13:20 UTC
Labels: duplicate
